#!/bin/bash

#wget -q --tries=3 ftp://ftp.uniprot.org/pub/databases/uniprot/current_release/knowledgebase/complete/uniprot_sprot.dat.gz
#sleep 5
#{ ERROR=$(gunzip -f uniprot_sprot.dat.gz 2>&1 1>&3-) ;} 3>&1
#if [ ! -z $ERROR ]; then
#        echo "Could not dowload uniprot_sprot.dat.gz"
#fi

#wget -q --tries=3 ftp://ftp.uniprot.org/pub/databases/uniprot/current_release/knowledgebase/complete/uniprot_trembl.dat.gz
#sleep 5
#{ ERROR=$(gunzip -f uniprot_trembl.dat.gz 2>&1 1>&3-) ;} 3>&1
#if [ ! -z $ERROR ]; then
#        echo "Could not dowload uniprot_sprot.dat.gz"
#fi

wget -q --tries=3 http://ftp.ebi.ac.uk/pub/databases/uniprot/current_release/knowledgebase/idmapping/idmapping_selected.tab.gz
sleep 5
7za e -y idmapping_selected.tab.gz
mkdir idmapping_selected
split -d -l 300000 idmapping_selected.tab idmapping_selected/

wget -q --tries=3 http://ftp.ebi.ac.uk/pub/databases/uniprot/current_release/knowledgebase/idmapping/idmapping.dat.gz
sleep 5
7za e -y idmapping.dat.gz
mkdir idmapping/
split -d -l 300000 idmapping.dat idmapping/

wget -q --tries=3 http://ftp.ebi.ac.uk/pub/databases/interpro/current/protein2ipr.dat.gz
sleep 5
7za e -y protein2ipr.dat.gz
mkdir protein2ipr
split -d -l 300000 protein2ipr.dat protein2ipr/

wget -q --tries=3 ftp://ftp.ncbi.nlm.nih.gov/gene/DATA/gene_info.gz
sleep 5
7za e -y gene_info.gz

wget -q --tries=3 -O go.obo http://purl.obolibrary.org/obo/go.obo

wget -q --tries=3 -O interpro_entrylist.txt ftp://ftp.ebi.ac.uk/pub/databases/interpro/current/entry.list

wget -q --tries=3 -O humdisease.txt http://ftp.ebi.ac.uk/pub/databases/uniprot/current_release/knowledgebase/complete/docs/humdisease.txt

wget -q --tries=3 -O ../normalized_data/pathway http://reactome.org/download/current/ReactomePathways.txt

wget -q --tries=3 -O ../normalized_data/pathway_hierarchy http://reactome.org/download/current/ReactomePathwaysRelation.txt

wget -q --tries=3 -O ParentChildTreeFile.txt ftp://ftp.ebi.ac.uk/pub/databases/interpro/ParentChildTreeFile.txt
touch ipr2parents.pl
chmod a+w ipr2parents.pl
perl ../ipr_parents.pl ParentChildTreeFile.txt > ipr2parents.pl

wget -q --tries=3 http://ftp.ncbi.nlm.nih.gov/pub/taxonomy/taxdump.tar.gz
tar xvfz taxdump.tar.gz
perl -e 'print "%tax2parent=(\n";while(<>){chomp;@arr=split(/\s+\|\s+/,$_); print "\t$arr[0]=>$arr[1],\n";};print ")\n";' nodes.dmp > tax2parent.pl
perl -e 'print "%tax2rank=(\n";while(<>){chomp;@arr=split(/\s+\|\s+/,$_); print "\t$arr[0]=>\"$arr[2]\",\n";};print ")\n";' nodes.dmp > tax2rank.pl
grep -i "scientific name" names.dmp | perl -e 'print "%tax2sciname=(\n";while(<>){chomp;@arr=split(/\s+\|\s+/,$_); print "\t$arr[0]=>\"$arr[1]\",\n";};print ")\n";' > tax2name.pl
