set autocommit=0;

truncate table PROTEIN_CROSSREF;
LOAD DATA LOCAL INFILE '/data01/comparative_proteomics_tool/normalized_data/protein_crossref2.tsv' replace INTO TABLE PROTEIN_CROSSREF FIELDS TERMINATED BY '\t' LINES TERMINATED BY '\n';
COMMIT;

ALTER TABLE PROTEIN_CROSSREF ADD PRIMARY KEY (ACCESSION,TYPE,CROSSREF);
COMMIT;

ALTER TABLE PROTEIN_CROSSREF ADD INDEX prot_cross_acc_idx (ACCESSION);
COMMIT;

ALTER TABLE PROTEIN_CROSSREF ADD INDEX prot_cross_type_idx (TYPE);
COMMIT;

ALTER TABLE PROTEIN_CROSSREF ADD INDEX prot_cross_crossref_idx (CROSSREF);
COMMIT;

ALTER TABLE PROTEIN_CROSSREF ADD CONSTRAINT fk_prot_cross_acc FOREIGN KEY (accession) REFERENCES PROTEIN(accession);
COMMIT;