
set autocommit=0;

truncate table PROTEIN;
LOAD DATA LOCAL INFILE '/data01/comparative_proteomics_tool/normalized_data/protein.tsv' replace INTO TABLE PROTEIN FIELDS TERMINATED BY '\t' LINES TERMINATED BY '\n';
COMMIT; 

truncate table PATHWAY_HIERARCHY;
LOAD DATA LOCAL INFILE '/data01/comparative_proteomics_tool/normalized_data/pathway_hierarchy.tsv' replace INTO TABLE PATHWAY_HIERARCHY FIELDS TERMINATED BY '\t' LINES TERMINATED BY '\n';
COMMIT;

truncate table PATHWAY;
LOAD DATA LOCAL INFILE '/data01/comparative_proteomics_tool/normalized_data/pathway.tsv' replace INTO TABLE PATHWAY FIELDS TERMINATED BY '\t' LINES TERMINATED BY '\n';
COMMIT;

truncate table PROTEIN_PATHWAY;
LOAD DATA LOCAL INFILE '/data01/comparative_proteomics_tool/normalized_data/protein_pathway.tsv' replace INTO TABLE PROTEIN_PATHWAY FIELDS TERMINATED BY '\t' LINES TERMINATED BY '\n';
COMMIT;

truncate table TAXON;
LOAD DATA LOCAL INFILE '/data01/comparative_proteomics_tool/normalized_data/taxon.tsv' replace INTO TABLE TAXON FIELDS TERMINATED BY '\t' LINES TERMINATED BY '\n';
COMMIT;

truncate table TAXON_HIERARCHY;
LOAD DATA LOCAL INFILE '/data01/comparative_proteomics_tool/normalized_data/taxon_hierarchy.tsv' replace INTO TABLE TAXON_HIERARCHY FIELDS TERMINATED BY '\t' LINES TERMINATED BY '\n';
COMMIT;

truncate table PROTEIN_PUBLICATION;
LOAD DATA LOCAL INFILE '/data01/comparative_proteomics_tool/normalized_data/protein_publication2.tsv' replace INTO TABLE PROTEIN_PUBLICATION FIELDS TERMINATED BY '\t' LINES TERMINATED BY '\n';
COMMIT;

truncate table PMID2AUTHOR;
LOAD DATA LOCAL INFILE '/data01/comparative_proteomics_tool/normalized_data/pmid2author2.tsv' replace INTO TABLE PMID2AUTHOR FIELDS TERMINATED BY '\t' LINES TERMINATED BY '\n';
COMMIT;

truncate table PUBLICATION;
LOAD DATA LOCAL INFILE '/data01/comparative_proteomics_tool/normalized_data/publications.tsv' replace INTO TABLE PUBLICATION FIELDS TERMINATED BY '\t' LINES TERMINATED BY '\n';
COMMIT;

truncate table PROTEIN_DISEASE;
LOAD DATA LOCAL INFILE '/data01/comparative_proteomics_tool/normalized_data/protein_disease.tsv' replace INTO TABLE PROTEIN_DISEASE FIELDS TERMINATED BY '\t' LINES TERMINATED BY '\n';
COMMIT;

truncate table DISEASE;
LOAD DATA LOCAL INFILE '/data01/comparative_proteomics_tool/normalized_data/disease.tsv' replace INTO TABLE DISEASE FIELDS TERMINATED BY '\t' LINES TERMINATED BY '\n';
COMMIT;

truncate table PROTEIN_PDB;
LOAD DATA LOCAL INFILE '/data01/comparative_proteomics_tool/normalized_data/protein_pdb2.tsv' replace INTO TABLE PROTEIN_PDB FIELDS TERMINATED BY '\t' LINES TERMINATED BY '\n';
COMMIT;

truncate table PROTEIN_GENE;
LOAD DATA LOCAL INFILE '/data01/comparative_proteomics_tool/normalized_data/protein_gene.tsv' replace INTO TABLE PROTEIN_GENE FIELDS TERMINATED BY '\t' LINES TERMINATED BY '\n';
COMMIT;

truncate table GENE;
LOAD DATA LOCAL INFILE '/data01/comparative_proteomics_tool/normalized_data/gene.tsv' replace INTO TABLE GENE FIELDS TERMINATED BY '\t' LINES TERMINATED BY '\n';
COMMIT;

truncate table NAMESPACE;
LOAD DATA LOCAL INFILE '/data01/comparative_proteomics_tool/normalized_data/namespace.tsv' replace INTO TABLE NAMESPACE FIELDS TERMINATED BY '\t' LINES TERMINATED BY '\n';
COMMIT;

truncate table PRIMARY2SECONDARY;
LOAD DATA LOCAL INFILE '/data01/comparative_proteomics_tool/normalized_data/primary2secondary.tsv' replace INTO TABLE PRIMARY2SECONDARY FIELDS TERMINATED BY '\t' LINES TERMINATED BY '\n';
COMMIT;

truncate table PROTEIN_DOMAIN;
LOAD DATA LOCAL INFILE '/data01/comparative_proteomics_tool/normalized_data/protein_domain.tsv' replace INTO TABLE PROTEIN_DOMAIN FIELDS TERMINATED BY '\t' LINES TERMINATED BY '\n';
COMMIT;

truncate table DOMAIN_COORDINATES;
LOAD DATA LOCAL INFILE '/data01/comparative_proteomics_tool/normalized_data/domain_coordinates.tsv' replace INTO TABLE DOMAIN_COORDINATES FIELDS TERMINATED BY '\t' LINES TERMINATED BY '\n';
COMMIT;

truncate table DOMAIN;
LOAD DATA LOCAL INFILE '/data01/comparative_proteomics_tool/normalized_data/domain.tsv' replace INTO TABLE DOMAIN FIELDS TERMINATED BY '\t' LINES TERMINATED BY '\n';
COMMIT;

truncate table GO_TERMS;
LOAD DATA LOCAL INFILE '/data01/comparative_proteomics_tool/normalized_data/go_terms.tsv' replace INTO TABLE GO_TERMS FIELDS TERMINATED BY '\t' LINES TERMINATED BY '\n';
COMMIT;

truncate table TERM_RELATIONS;
LOAD DATA LOCAL INFILE '/data01/comparative_proteomics_tool/normalized_data/term_relations.tsv' replace INTO TABLE TERM_RELATIONS FIELDS TERMINATED BY '\t' LINES TERMINATED BY '\n';
COMMIT;

truncate table PROTEIN_ONTOLOGY;
LOAD DATA LOCAL INFILE '/data01/comparative_proteomics_tool/normalized_data/protein_ontology2.tsv' replace INTO TABLE PROTEIN_ONTOLOGY FIELDS TERMINATED BY '\t' LINES TERMINATED BY '\n';
COMMIT;

truncate table MOLFUNC;
LOAD DATA LOCAL INFILE '/data01/comparative_proteomics_tool/normalized_data/molecular_function.tsv' replace INTO TABLE MOLFUNC FIELDS TERMINATED BY '\t' LINES TERMINATED BY '\n';
COMMIT;

truncate table BIOPROC;
LOAD DATA LOCAL INFILE '/data01/comparative_proteomics_tool/normalized_data/biological_process.tsv' replace INTO TABLE BIOPROC FIELDS TERMINATED BY '\t' LINES TERMINATED BY '\n';
COMMIT;

truncate table PFAM;
LOAD DATA LOCAL INFILE '/data01/comparative_proteomics_tool/normalized_data/pfam.tsv' replace INTO TABLE PFAM FIELDS TERMINATED BY '\t' LINES TERMINATED BY '\n';
COMMIT;

truncate table REACTOME;
LOAD DATA LOCAL INFILE '/data01/comparative_proteomics_tool/normalized_data/reactome.tsv' replace INTO TABLE REACTOME FIELDS TERMINATED BY '\t' LINES TERMINATED BY '\n';
COMMIT;

truncate table PROT;
LOAD DATA LOCAL INFILE '/data01/comparative_proteomics_tool/normalized_data/prot.tsv' replace INTO TABLE PROT FIELDS TERMINATED BY '\t' LINES TERMINATED BY '\n';
COMMIT;



ALTER TABLE MOLFUNC ADD PRIMARY KEY (GO_MOLFUNC);
COMMIT; 

ALTER TABLE BIOPROC ADD PRIMARY KEY (GO_BIOPROC);
COMMIT; 

ALTER TABLE PFAM ADD PRIMARY KEY (PFAM_ID,IPR_ID);
COMMIT; 

ALTER TABLE REACTOME ADD PRIMARY KEY (ID,SPEC);
COMMIT; 

ALTER TABLE PROT ADD PRIMARY KEY (ACC);
COMMIT; 

ALTER TABLE PROTEIN ADD PRIMARY KEY (ACCESSION);
COMMIT; 

ALTER TABLE PATHWAY_HIERARCHY ADD PRIMARY KEY (PARENT_ID,CHILD_ID,PARENT_SPEC);
COMMIT; 

ALTER TABLE PATHWAY ADD PRIMARY KEY (ID,SPECIES);
COMMIT;

ALTER TABLE PROTEIN_PATHWAY ADD PRIMARY KEY (ACCESSION,PATHWAY);
COMMIT;

ALTER TABLE TAXON ADD PRIMARY KEY (ID);
COMMIT;

ALTER TABLE TAXON_HIERARCHY ADD PRIMARY KEY (CHILD,PARENT);
COMMIT;

ALTER TABLE PROTEIN_PUBLICATION ADD PRIMARY KEY (ACCESSION,PMID);
COMMIT;

ALTER TABLE PMID2AUTHOR ADD PRIMARY KEY (PUBLICATION_PMID,AUTHOR_NAME);
COMMIT;

ALTER TABLE PUBLICATION ADD PRIMARY KEY (PMID);
COMMIT;

ALTER TABLE PROTEIN_DISEASE ADD PRIMARY KEY (ACCESSION,MIM);
COMMIT;

ALTER TABLE DISEASE ADD PRIMARY KEY (ACC,MIM);
COMMIT;

ALTER TABLE PROTEIN_PDB ADD PRIMARY KEY (ACCESSION,PDB,CHAIN);
COMMIT;

ALTER TABLE PROTEIN_GENE ADD PRIMARY KEY (ACCESSION,GENE);
COMMIT;

ALTER TABLE GENE ADD PRIMARY KEY (ID);
COMMIT;

ALTER TABLE NAMESPACE ADD PRIMARY KEY (NAMESPACE);
COMMIT;

ALTER TABLE PRIMARY2SECONDARY ADD PRIMARY KEY (PRIMARY_ACCESSION,SECONDARY_ACCESSION);
COMMIT;

ALTER TABLE PROTEIN_DOMAIN ADD PRIMARY KEY (ACCESSION,DOMAIN);
COMMIT;

ALTER TABLE DOMAIN_COORDINATES ADD PRIMARY KEY (ACCESSION,DOMAIN,START,END);
COMMIT;

ALTER TABLE DOMAIN ADD PRIMARY KEY (PFAM,IPR_ID);
COMMIT;

ALTER TABLE GO_TERMS ADD PRIMARY KEY (TERM_ID);
COMMIT;

ALTER TABLE TERM_RELATIONS ADD PRIMARY KEY (TERM_ID,IS_A);
COMMIT;

ALTER TABLE PROTEIN_ONTOLOGY ADD PRIMARY KEY (ACCESSION,ONTOLOGY);
COMMIT;




ALTER TABLE PROTEIN ADD INDEX protein_id_idx (ID);
COMMIT;

ALTER TABLE PROTEIN ADD INDEX protein_taxon_idx (TAXON_ID);
COMMIT;

CREATE FULLTEXT INDEX protein_name_idx ON PROTEIN (NAME);
COMMIT;

ALTER TABLE PROTEIN_PATHWAY ADD INDEX prot_pathway_pathway_idx (PATHWAY);
COMMIT;

ALTER TABLE PROTEIN_PATHWAY ADD INDEX prot_pathway_acc_idx (ACCESSION);
COMMIT;

CREATE FULLTEXT INDEX taxon_name_idx ON TAXON (NAME);
COMMIT;

ALTER TABLE TAXON_HIERARCHY ADD INDEX tax_h_parent_idx (PARENT);
COMMIT;

ALTER TABLE PATHWAY ADD INDEX pathway_name_idx (NAME);
COMMIT;

ALTER TABLE PATHWAY_HIERARCHY ADD INDEX pathwayh_child_idx (child_id);
COMMIT;

ALTER TABLE PROTEIN_PDB ADD INDEX pdb_idx (PDB);
COMMIT;

ALTER TABLE PROTEIN_PDB ADD INDEX pdb_chain_idx (CHAIN);
COMMIT;

ALTER TABLE GO_TERMS ADD INDEX go_name_idx (NAME);
COMMIT;

ALTER TABLE GO_TERMS ADD INDEX go_namespace_idx (NAMESPACE);
COMMIT;

CREATE FULLTEXT INDEX go_def_idx ON GO_TERMS (DEFINITION);
COMMIT;

CREATE FULLTEXT INDEX gene_sym_idx ON GENE (SYMBOL);
COMMIT;

CREATE FULLTEXT INDEX gene_desc_idx ON GENE (DESCRIPTION);
COMMIT;

ALTER TABLE PROTEIN_ONTOLOGY ADD INDEX protontology_acc_idx (ACCESSION);
COMMIT;

ALTER TABLE PROTEIN_ONTOLOGY ADD INDEX protontology_ontology_idx (ONTOLOGY);
COMMIT;

ALTER TABLE TERM_RELATIONS ADD INDEX termrelations_isa_idx (is_a);
COMMIT;

ALTER TABLE PROTEIN_DOMAIN ADD INDEX protdomain_idx (DOMAIN);
COMMIT;

ALTER TABLE DOMAIN ADD INDEX domain_ipr_idx (IPR_ID);
COMMIT;

CREATE FULLTEXT INDEX domain_name_idx ON DOMAIN (NAME);
COMMIT;

ALTER TABLE PROTEIN_PUBLICATION ADD INDEX protpub_pmid_idx (pmid);
COMMIT;

ALTER TABLE PROTEIN_DISEASE ADD INDEX protdisease_mim_idx (MIM);
COMMIT;

CREATE FULLTEXT INDEX disease_acroynm_idx ON DISEASE (ACRONYM);
COMMIT;

CREATE FULLTEXT INDEX disease_identifier_idx ON DISEASE (IDENTIFIER);
COMMIT;

CREATE FULLTEXT INDEX disease_def_idx ON DISEASE (DEFINITION);
COMMIT;

ALTER TABLE DISEASE ADD INDEX disease_mim_idx (MIM);
COMMIT;



ALTER TABLE PATHWAY_HIERARCHY ADD CONSTRAINT fk_path_parent FOREIGN KEY (parent_id) REFERENCES PATHWAY(id);
COMMIT;

ALTER TABLE PATHWAY_HIERARCHY ADD CONSTRAINT fk_path_child FOREIGN KEY (child_id) REFERENCES PATHWAY(id);
COMMIT;

ALTER TABLE TAXON_HIERARCHY ADD CONSTRAINT fk_tax_child FOREIGN KEY (child) REFERENCES TAXON(id);
COMMIT;

ALTER TABLE TAXON_HIERARCHY ADD CONSTRAINT fk_tax_parent FOREIGN KEY (parent) REFERENCES TAXON(id);
COMMIT;

ALTER TABLE PROTEIN_PUBLICATION ADD CONSTRAINT fk_prot_pub_acc FOREIGN KEY (accession) REFERENCES PROTEIN(accession);
COMMIT;

ALTER TABLE PROTEIN_PUBLICATION ADD CONSTRAINT fk_prot_pub_pmid FOREIGN KEY (pmid) REFERENCES PUBLICATION(pmid);
COMMIT;

ALTER TABLE PROTEIN_PATHWAY ADD CONSTRAINT fk_prot_path_acc FOREIGN KEY (accession) REFERENCES PROTEIN(accession);
COMMIT;

ALTER TABLE PROTEIN_PATHWAY ADD CONSTRAINT fk_prot_path_id FOREIGN KEY (pathway) REFERENCES PATHWAY(id);
COMMIT;

ALTER TABLE PROTEIN_DISEASE ADD CONSTRAINT fk_prot_disease_acc FOREIGN KEY (accession) REFERENCES PROTEIN(accession);
COMMIT;

ALTER TABLE PROTEIN_DISEASE ADD CONSTRAINT fk_prot_disease_mim FOREIGN KEY (MIM) REFERENCES DISEASE(MIM);
COMMIT;

ALTER TABLE PROTEIN_GENE ADD CONSTRAINT fk_prot_gene_acc FOREIGN KEY (accession) REFERENCES PROTEIN(accession);
COMMIT;

ALTER TABLE PROTEIN_PDB ADD CONSTRAINT fk_prot_pdb_acc FOREIGN KEY (accession) REFERENCES PROTEIN(accession);
COMMIT;

ALTER TABLE PROTEIN_ONTOLOGY ADD CONSTRAINT fk_prot_go_acc FOREIGN KEY (accession) REFERENCES PROTEIN(accession);
COMMIT;

ALTER TABLE PROTEIN_ONTOLOGY ADD CONSTRAINT fk_prot_go_id FOREIGN KEY (ontology) REFERENCES GO_TERMS(term_id);
COMMIT;

ALTER TABLE TERM_RELATIONS ADD CONSTRAINT fk_go_id FOREIGN KEY (term_id) REFERENCES GO_TERMS(term_id);
COMMIT;

ALTER TABLE TERM_RELATIONS ADD CONSTRAINT fk_go_isa FOREIGN KEY (is_a) REFERENCES GO_TERMS(term_id);
COMMIT;

ALTER TABLE PRIMARY2SECONDARY ADD CONSTRAINT fk_prisec_acc FOREIGN KEY (PRIMARY_ACCESSION) REFERENCES PROTEIN(accession);
COMMIT;

ALTER TABLE PMID2AUTHOR ADD CONSTRAINT fk_pmid2author_pmid FOREIGN KEY (publication_pmid) REFERENCES PUBLICATION(pmid);
COMMIT;

ALTER TABLE GO_TERMS ADD CONSTRAINT fk_goterms_namespace FOREIGN KEY (NAMESPACE) REFERENCES NAMESPACE(NAMESPACE);
COMMIT;




